/**
 * The backdrop library.
 *
 * Pure data, generated by tools/backdrops/generate.js and kept in sync with
 * public/backdrops/manifest.json. `scenes.background_image_url` has been in the
 * schema since migration 001 and the player renders it, but no images shipped —
 * so the feature was reachable and empty.
 */

export type BackdropCategory = 'outdoor' | 'space' | 'water' | 'indoor' | 'fantasy' | 'abstract';

export interface Backdrop {
  id: string;
  name: string;
  category: BackdropCategory;
  url: string;
}

export const BACKDROPS: Backdrop[] = [
  { id: 'blue-sky', name: 'Blue Sky', category: 'outdoor', url: '/backdrops/blue-sky.svg' },
  { id: 'sunset', name: 'Sunset', category: 'outdoor', url: '/backdrops/sunset.svg' },
  { id: 'green-hills', name: 'Green Hills', category: 'outdoor', url: '/backdrops/green-hills.svg' },
  { id: 'beach', name: 'Beach', category: 'outdoor', url: '/backdrops/beach.svg' },
  { id: 'desert', name: 'Desert', category: 'outdoor', url: '/backdrops/desert.svg' },
  { id: 'snow', name: 'Snowy', category: 'outdoor', url: '/backdrops/snow.svg' },
  { id: 'forest', name: 'Forest', category: 'outdoor', url: '/backdrops/forest.svg' },
  { id: 'night-sky', name: 'Night Sky', category: 'space', url: '/backdrops/night-sky.svg' },
  { id: 'outer-space', name: 'Outer Space', category: 'space', url: '/backdrops/outer-space.svg' },
  { id: 'underwater', name: 'Underwater', category: 'water', url: '/backdrops/underwater.svg' },
  { id: 'city', name: 'City', category: 'indoor', url: '/backdrops/city.svg' },
  { id: 'room', name: 'Room', category: 'indoor', url: '/backdrops/room.svg' },
  { id: 'castle', name: 'Castle', category: 'fantasy', url: '/backdrops/castle.svg' },
  { id: 'cave', name: 'Cave', category: 'fantasy', url: '/backdrops/cave.svg' },
  { id: 'rainbow', name: 'Rainbow', category: 'abstract', url: '/backdrops/rainbow.svg' },
  { id: 'grid', name: 'Grid', category: 'abstract', url: '/backdrops/grid.svg' },
];

export const BACKDROP_CATEGORIES: BackdropCategory[] = [
  'outdoor', 'space', 'water', 'indoor', 'fantasy', 'abstract',
];

export function backdropsByCategory(category: BackdropCategory): Backdrop[] {
  return BACKDROPS.filter((b) => b.category === category);
}

/** Resolve a backdrop by id or by url — scenes store the url. */
export function findBackdrop(value: string | null | undefined): Backdrop | undefined {
  if (!value) return undefined;
  const v = String(value).trim();
  return BACKDROPS.find((b) => b.id === v || b.url === v);
}
