import type { ModelBounds, ModelOriginOffset } from '../models/modelRenderContract';
import { STARTER_MODEL_METADATA } from './generatedStarterModels';

/**
 * Pull the auto-generated model_url + bounds + origin_offset for a metal-starters
 * character. Regenerated by `npm run generate:starters`; bounds must NOT be
 * hand-edited — they're the source of truth for the shipped GLB.
 */
function starterModel(id: keyof typeof STARTER_MODEL_METADATA): {
  model_url: string;
  model_bounds: ModelBounds;
  model_origin_offset: ModelOriginOffset;
} {
  const m = STARTER_MODEL_METADATA[id];
  return {
    model_url: m.model_url,
    model_bounds: m.model_bounds as ModelBounds,
    model_origin_offset: m.model_origin_offset as ModelOriginOffset,
  };
}

// Humanoids from metal-starters render at ~1.76u tall at size=1, so size=34
// puts a picker character at roughly 0.6u tall (matches the primitive-era
// capsule size). Tweak per character if a specific silhouette needs it.
const HUMANOID_SIZE = 34;

/**
 * Built-in character library. Kept as a shared module so both the
 * CharacterSelector picker (client) and the /api/ai/generate-character route
 * (server) look up the SAME prefabs — the AI never invents a new shape when
 * we already have a matching one on the shelf.
 *
 * When a kid asks for "a wizard", we should return our Wizard cone in ~1ms
 * for free, not spend 30 seconds and dollars generating a novel 3D mesh.
 */

export interface CharacterPrefab {
  id: string;
  name: string;
  color: string;
  shape: string;
  /** Optional local or uploaded GLB/FBX model for this character. */
  model_url?: string;
  /** Local-space measurements for consistent editor/player rendering. */
  model_bounds?: ModelBounds;
  /** Local translation that places the model's feet on its object origin. */
  model_origin_offset?: ModelOriginOffset;
  size: number;
  description: string;
  /** Extra keywords that also count as a match (case-insensitive). */
  aliases?: string[];
  /** Optional 3D preview transform (used only by the picker thumbnail). */
  preview_scale?: number;
  preview_rotation?: [number, number, number];
}

interface CharacterVisualInput {
  shape?: string;
  color?: string;
  size?: number;
  model_url?: string;
  thumbnail_url?: string;
  properties?: Record<string, unknown>;
}

/** Build the visual fields persisted when a picker character is selected. */
export function buildCharacterVisualData(character: CharacterVisualInput) {
  if (character.model_url) {
    const size = character.size || 1;
    const modelData = {
      shape: 'model',
      model_url: character.model_url,
      thumbnail_url: character.thumbnail_url,
      size,
    };
    return {
      sprite_data: modelData,
      properties: { ...modelData },
    };
  }

  const size = character.size || 50;
  return {
    sprite_data: {
      shape: character.shape || 'box',
      color: character.color,
      size,
    },
    properties: {
      ...(character.properties || {}),
      shape: character.shape || 'box',
      color: character.color,
      size,
    },
  };
}

/** Named starter characters. Order matters for the picker grid. */
export const CHARACTER_TEMPLATES: CharacterPrefab[] = [
  // Humanoids — bounds/origin flow from metal-starters (STARTER_MODEL_METADATA).
  // Picker preview uses the multi-part GLB; `shape` is only the SVG fallback if
  // the model fails to load. buildCharacterVisualData overrides shape to 'model'
  // for persistence.
  {
    id: 'hero',
    name: 'Hero',
    color: '#60A5FA',
    shape: 'capsule',
    ...starterModel('hero'),
    size: HUMANOID_SIZE,
    description: 'Standing hero',
    aliases: ['protagonist', 'main character', 'player', 'good guy'],
  },
  {
    id: 'knight',
    name: 'Knight',
    color: '#3B82F6',
    shape: 'capsule',
    ...starterModel('knight'),
    size: HUMANOID_SIZE,
    description: 'Armoured warrior',
    aliases: ['warrior', 'soldier', 'guard', 'paladin'],
  },
  {
    id: 'wizard',
    name: 'Wizard',
    color: '#8B5CF6',
    shape: 'capsule',
    ...starterModel('wizard'),
    size: HUMANOID_SIZE,
    description: 'Pointy-hatted mage',
    aliases: ['mage', 'sorcerer', 'witch', 'magician', 'spellcaster'],
  },
  {
    id: 'robot',
    name: 'Robot',
    color: '#6B7280',
    shape: 'capsule',
    ...starterModel('robot'),
    size: HUMANOID_SIZE,
    description: 'Mechanical body',
    aliases: ['bot', 'android', 'droid', 'mech', 'automaton', 'machine'],
  },
  {
    id: 'ninja',
    name: 'Ninja',
    color: '#1F2937',
    shape: 'capsule',
    ...starterModel('ninja'),
    size: HUMANOID_SIZE,
    description: 'Stealthy runner',
    aliases: ['assassin', 'spy', 'stealth'],
  },
  {
    id: 'alien',
    name: 'Alien',
    color: '#10B981',
    shape: 'sphere',
    ...starterModel('alien'),
    size: 50,
    description: 'Little green visitor',
    aliases: ['extraterrestrial', 'ufo', 'martian', 'et'],
  },
  {
    id: 'princess',
    name: 'Princess',
    color: '#EC4899',
    shape: 'capsule',
    ...starterModel('princess'),
    size: HUMANOID_SIZE,
    description: 'Regal royal',
    aliases: ['queen', 'royalty', 'monarch'],
  },
  {
    id: 'astronaut',
    name: 'Astronaut',
    color: '#F3F4F6',
    shape: 'capsule',
    ...starterModel('astronaut'),
    size: HUMANOID_SIZE,
    description: 'Space explorer',
    aliases: ['spaceman', 'cosmonaut', 'space explorer'],
  },
  {
    id: 'superhero',
    name: 'Superhero',
    color: '#1D4ED8',
    shape: 'capsule',
    ...starterModel('superhero'),
    size: HUMANOID_SIZE,
    description: 'Caped defender',
    aliases: ['super', 'super hero', 'caped hero', 'flying hero'],
  },
  {
    id: 'minion',
    name: 'Minion',
    color: '#FACC15',
    shape: 'model',
    size: 14,
    description: 'Cheerful yellow helper',
    aliases: ['yellow helper', 'banana buddy'],
    model_url: '/models/minion/FBX/Minion_FBX.fbx',
    preview_scale: 0.14,
    preview_rotation: [0, 0, 0],
  },
  // Creatures — colors are overridden by any color word in the prompt (see
  // extractColor below). The dragon uses the checked-in Metal-generated GLB;
  // the others fall back to primitives until real models ship.
  // Dragon — checked-in multi-part GLB from the metal-dragon tool (see
  // tools/metal-dragon/). Regenerate with `bash tools/metal-dragon/generate.sh`;
  // bounds must stay in sync with the file (see test/editor/model-render-contract.test.js).
  {
    id: 'dragon',
    name: 'Red Metal Dragon',
    color: '#DC2626',
    shape: 'capsule',
    model_url: '/models/red-metal-dragon.glb',
    model_bounds: {
      min: { x: -2.982, y: -1.836, z: -1.983 },
      max: { x: 2.82, y: 2.362, z: 1.983 },
    },
    model_origin_offset: { x: 0, y: 1.836, z: 0 },
    size: 28,
    description: 'Fire-breathing dragon',
    aliases: ['drake', 'wyrm', 'wyvern'],
  },
  {
    id: 'monster',
    name: 'Monster',
    color: '#7C3AED',
    shape: 'sphere',
    ...starterModel('monster'),
    size: 50,
    description: 'One-eyed monster',
    aliases: ['creature', 'beast', 'ogre', 'troll', 'goblin', 'blob'],
  },
  {
    id: 'ghost',
    name: 'Ghost',
    color: '#E5E7EB',
    shape: 'capsule',
    ...starterModel('ghost'),
    size: 55,
    description: 'Floaty spirit',
    aliases: ['spirit', 'phantom', 'spook', 'boo'],
  },
  // Animals — quadrupeds share the metal-starters quadruped() template; fish/bird
  // have dedicated templates. Sizes calibrated so each reads at ~0.6-0.7u tall.
  {
    id: 'fish',
    name: 'Fish',
    color: '#60A5FA',
    shape: 'capsule',
    ...starterModel('fish'),
    size: 70,
    description: 'Tiny swimmer',
    aliases: ['minnow', 'guppy', 'goldfish', 'trout'],
  },
  {
    id: 'dog',
    name: 'Dog',
    color: '#F59E0B',
    shape: 'capsule',
    ...starterModel('dog'),
    size: 50,
    description: 'Loyal pup',
    aliases: ['doggy', 'hound', 'canine'],
  },
  {
    id: 'puppy',
    name: 'Puppy',
    color: '#F59E0B',
    shape: 'capsule',
    ...starterModel('puppy'),
    size: 55,
    description: 'Little pup',
    aliases: ['pup'],
  },
  {
    id: 'cat',
    name: 'Cat',
    color: '#F97316',
    shape: 'capsule',
    ...starterModel('cat'),
    size: 55,
    description: 'Sneaky feline',
    aliases: ['kitten', 'kitty', 'feline'],
  },
  {
    id: 'bird',
    name: 'Bird',
    color: '#38BDF8',
    shape: 'sphere',
    ...starterModel('bird'),
    size: 55,
    description: 'Small bird',
    aliases: ['sparrow', 'robin', 'chick', 'chirper'],
  },
  {
    id: 'dinosaur',
    name: 'Dinosaur',
    color: '#16A34A',
    shape: 'capsule',
    ...starterModel('dinosaur'),
    size: 42,
    description: 'Friendly dino',
    aliases: ['dino', 't-rex', 'trex'],
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    color: '#F0ABFC',
    shape: 'capsule',
    ...starterModel('unicorn'),
    size: 40,
    description: 'Magical unicorn',
    aliases: ['pony', 'horse'],
  },
  {
    id: 'tree',
    name: 'Tree',
    color: '#16A34A',
    shape: 'cone',
    ...starterModel('tree'),
    size: 70,
    description: 'Leafy tree',
    aliases: ['bush', 'shrub', 'pine', 'fir'],
  },
  {
    id: 'rock',
    name: 'Rock',
    color: '#57534E',
    shape: 'sphere',
    ...starterModel('rock'),
    size: 55,
    description: 'Boulder',
    aliases: ['stone', 'pebble'],
  },
];

/**
 * A tiny color-word extractor for prompt strings. Used by the AI-character
 * route when neither a prefab match nor Meshy nor Claude produces a real
 * color — instead of picking a random one, we honor the color word the kid
 * actually typed.
 *
 * Returns null when no color word is present.
 */
export function extractColor(prompt: string): string | null {
  const t = prompt.toLowerCase();
  const map: Array<[RegExp, string]> = [
    [/\bred\b|\bcrimson\b|\bruby\b|\bscarlet\b/, '#EF4444'],
    [/\borange\b|\bamber\b/, '#F97316'],
    [/\byellow\b|\bgold(en)?\b/, '#FACC15'],
    [/\bgreen\b|\bemerald\b|\blime\b/, '#22C55E'],
    [/\bblue\b|\bazure\b|\bsapphire\b|\bnavy\b/, '#3B82F6'],
    [/\bpurple\b|\bviolet\b|\bindigo\b|\bmagenta\b/, '#8B5CF6'],
    [/\bpink\b|\brose\b/, '#EC4899'],
    [/\bwhite\b|\bsnow\b|\bpale\b/, '#F3F4F6'],
    [/\bblack\b|\bshadow\b|\bdark\b/, '#111827'],
    [/\bgrey\b|\bgray\b|\bsilver\b/, '#9CA3AF'],
    [/\bbrown\b|\btan\b/, '#92400E'],
    [/\bcyan\b|\bturquoise\b|\bteal\b/, '#06B6D4'],
  ];
  for (const [re, hex] of map) if (re.test(t)) return hex;
  return null;
}

/** Raw primitive shapes — matched when the prompt names a shape directly. */
export const BASIC_SHAPES: CharacterPrefab[] = [
  { id: 'cube', name: 'Cube', color: '#60A5FA', shape: 'box', size: 60, description: 'Boxy character', aliases: ['box', 'block', 'square'] },
  { id: 'sphere', name: 'Ball', color: '#F59E0B', shape: 'sphere', size: 60, description: 'Round rolling ball', aliases: ['sphere', 'orb', 'globe'] },
  { id: 'cylinder', name: 'Barrel', color: '#34D399', shape: 'cylinder', size: 60, description: 'Barrel-shaped body', aliases: ['cylinder', 'tube', 'can'] },
  { id: 'cone', name: 'Cone', color: '#A78BFA', shape: 'cone', size: 60, description: 'Pointy top', aliases: ['pointy', 'triangle'] },
  { id: 'pyramid', name: 'Pyramid', color: '#F472B6', shape: 'pyramid', size: 60, description: 'Four-sided pyramid', aliases: ['tetrahedron'] },
  { id: 'torus', name: 'Ring', color: '#FBBF24', shape: 'torus', size: 60, description: 'Donut ring', aliases: ['donut', 'doughnut', 'ring'] },
  { id: 'capsule', name: 'Capsule', color: '#60A5FA', shape: 'capsule', size: 60, description: 'Standing pill', aliases: ['pill'] },
];

/**
 * Best-effort prefab match. Returns the closest CHARACTER_TEMPLATES or
 * BASIC_SHAPES entry, or null if nothing matches confidently.
 *
 * Match strategy (fastest → loosest):
 *   1. Exact id / name match
 *   2. Case-insensitive substring of id / name / alias in the prompt
 *   3. Prompt tokens overlap with name/description/aliases
 *
 * Returns null instead of guessing when confidence is low, so the caller can
 * fall through to Meshy or the AI-property path.
 */
export function matchCharacterPrefab(prompt: string): CharacterPrefab | null {
  const normalized = prompt.trim().toLowerCase();
  if (!normalized) return null;

  const pool = [...CHARACTER_TEMPLATES, ...BASIC_SHAPES];
  const words = normalized.split(/[^a-z0-9]+/).filter(Boolean);
  const wordSet = new Set(words);
  const matchesKeyword = (keyword: string) => {
    const normalizedKeyword = keyword.toLowerCase();
    return normalizedKeyword.includes(' ')
      ? normalized.includes(normalizedKeyword)
      : wordSet.has(normalizedKeyword);
  };

  // A model-backed match wins over primitives; within the model pool, an id or
  // name match beats an alias match so compound prompts resolve to the primary
  // noun ("a knight riding a wyvern" → knight, not dragon-via-wyvern-alias;
  // "red dragon warrior" → dragon, not knight-via-warrior-alias). Ties break by
  // catalog order (first declared wins), matching picker grid order.
  let bestModel: { prefab: CharacterPrefab; score: number } | null = null;
  for (const prefab of pool) {
    if (!prefab.model_url) continue;
    let score = 0;
    if (matchesKeyword(prefab.id) || matchesKeyword(prefab.name)) score = 2;
    else if ((prefab.aliases ?? []).some(matchesKeyword)) score = 1;
    if (score > (bestModel?.score ?? 0)) bestModel = { prefab, score };
  }
  if (bestModel) return bestModel.prefab;

  // Tier 1: exact id or name.
  for (const p of pool) {
    if (p.id === normalized || p.name.toLowerCase() === normalized) return p;
  }

  // Tier 2: any keyword (id, name, alias) appears as a whole-word match.
  for (const p of pool) {
    const keywords = [p.id, p.name.toLowerCase(), ...(p.aliases ?? [])];
    for (const k of keywords) {
      // Whole-word check — "hero" matches "a brave hero" but not "heroic".
      if (matchesKeyword(k)) return p;
    }
  }

  return null;
}

/** Builds the exact prefab-first payload returned by generate-character. */
export function buildPrefabCharacterResponse(prompt: string, prefab: CharacterPrefab) {
  return {
    ...prefab,
    color: extractColor(prompt) ?? prefab.color,
    name: prompt.length > 2 ? prompt : prefab.name,
    source: 'prefab' as const,
  };
}
