import type { ModelBounds, ModelOriginOffset } from '../models/modelRenderContract';
import { STARTER_MODEL_METADATA } from './generatedStarterModels';

/**
 * Pull the auto-generated model_url + bounds + origin_offset for a metal-starters
 * character. Regenerated by `npm run generate:starters`; bounds must NOT be
 * hand-edited — they're the source of truth for the shipped GLB.
 */
function starterModel(id: keyof typeof STARTER_MODEL_METADATA): {
  model_url: string;
  model_bounds: ModelBounds;
  model_origin_offset: ModelOriginOffset;
} {
  const m = STARTER_MODEL_METADATA[id];
  return {
    model_url: m.model_url,
    model_bounds: m.model_bounds as ModelBounds,
    model_origin_offset: m.model_origin_offset as ModelOriginOffset,
  };
}

// Humanoids from metal-starters render at ~1.76u tall at size=1, so size=34
// puts a picker character at roughly 0.6u tall (matches the primitive-era
// capsule size). Tweak per character if a specific silhouette needs it.
/**
 * How large a starter appears in the world, derived from the model itself.
 *
 * Every starter used to carry a hand-tuned `size` — 28, 34, 50, 55, 60 — and
 * they varied only because each had been nudged until it rendered about 0.6
 * world units tall. That target was inherited from the primitive-shape era,
 * before these were real models, and nobody revisited it: on the 20-unit scene
 * grid a character came out at roughly 3% of the grid, which is a speck. For
 * comparison, a default Scratch sprite is about 28% of the stage height.
 *
 * Scaling to the largest dimension rather than the height keeps proportions
 * sensible — a car is long, not tall, and normalising by height alone would
 * make flat things enormous.
 *
 * Only the default for newly added objects changes. Every existing object
 * stores its own size and is untouched.
 */
const TARGET_EXTENT_UNITS = 2.4;

function starterSize(id: keyof typeof STARTER_MODEL_METADATA): number {
  const bounds = STARTER_MODEL_METADATA[id]?.model_bounds;
  if (!bounds) return 100;
  const extent = Math.max(
    bounds.max.x - bounds.min.x,
    bounds.max.y - bounds.min.y,
    bounds.max.z - bounds.min.z
  );
  return extent > 0 ? Math.round((TARGET_EXTENT_UNITS / extent) * 100) : 100;
}

/**
 * Built-in character library. Kept as a shared module so both the
 * CharacterSelector picker (client) and the /api/ai/generate-character route
 * (server) look up the SAME prefabs — the AI never invents a new shape when
 * we already have a matching one on the shelf.
 *
 * When a kid asks for "a wizard", we should return our Wizard cone in ~1ms
 * for free, not spend 30 seconds and dollars generating a novel 3D mesh.
 */

export interface CharacterPrefab {
  id: string;
  name: string;
  color: string;
  shape: string;
  /** Optional local or uploaded GLB/FBX model for this character. */
  model_url?: string;
  /** Local-space measurements for consistent editor/player rendering. */
  model_bounds?: ModelBounds;
  /** Local translation that places the model's feet on its object origin. */
  model_origin_offset?: ModelOriginOffset;
  size: number;
  description: string;
  /** Extra keywords that also count as a match (case-insensitive). */
  aliases?: string[];
  /** Optional 3D preview transform (used only by the picker thumbnail). */
  preview_scale?: number;
  preview_rotation?: [number, number, number];
}

interface CharacterVisualInput {
  shape?: string;
  color?: string;
  size?: number;
  model_url?: string;
  thumbnail_url?: string;
  properties?: Record<string, unknown>;
}

/** Build the visual fields persisted when a picker character is selected. */
export function buildCharacterVisualData(character: CharacterVisualInput) {
  if (character.model_url) {
    const size = character.size || 1;
    const modelData = {
      shape: 'model',
      model_url: character.model_url,
      thumbnail_url: character.thumbnail_url,
      size,
    };
    return {
      sprite_data: modelData,
      properties: { ...modelData },
    };
  }

  const size = character.size || 50;
  return {
    sprite_data: {
      shape: character.shape || 'box',
      color: character.color,
      size,
    },
    properties: {
      ...(character.properties || {}),
      shape: character.shape || 'box',
      color: character.color,
      size,
    },
  };
}

/** Named starter characters. Order matters for the picker grid. */
export const CHARACTER_TEMPLATES: CharacterPrefab[] = [
  // Humanoids — bounds/origin flow from metal-starters (STARTER_MODEL_METADATA).
  // Picker preview uses the multi-part GLB; `shape` is only the SVG fallback if
  // the model fails to load. buildCharacterVisualData overrides shape to 'model'
  // for persistence.
  {
    id: 'hero',
    name: 'Hero',
    color: '#60A5FA',
    shape: 'capsule',
    ...starterModel('hero'),
    size: starterSize('hero'),
    description: 'Standing hero',
    aliases: ['protagonist', 'main character', 'player', 'good guy'],
  },
  {
    id: 'knight',
    name: 'Knight',
    color: '#3B82F6',
    shape: 'capsule',
    ...starterModel('knight'),
    size: starterSize('knight'),
    description: 'Armoured warrior',
    aliases: ['warrior', 'soldier', 'guard', 'paladin'],
  },
  {
    id: 'wizard',
    name: 'Wizard',
    color: '#8B5CF6',
    shape: 'capsule',
    ...starterModel('wizard'),
    size: starterSize('wizard'),
    description: 'Pointy-hatted mage',
    aliases: ['mage', 'sorcerer', 'witch', 'magician', 'spellcaster'],
  },
  {
    id: 'robot',
    name: 'Robot',
    color: '#6B7280',
    shape: 'capsule',
    ...starterModel('robot'),
    size: starterSize('robot'),
    description: 'Mechanical body',
    aliases: ['bot', 'android', 'droid', 'mech', 'automaton', 'machine'],
  },
  {
    id: 'ninja',
    name: 'Ninja',
    color: '#1F2937',
    shape: 'capsule',
    ...starterModel('ninja'),
    size: starterSize('ninja'),
    description: 'Stealthy runner',
    aliases: ['assassin', 'spy', 'stealth'],
  },
  {
    id: 'alien',
    name: 'Alien',
    color: '#10B981',
    shape: 'sphere',
    ...starterModel('alien'),
    size: starterSize('alien'),
    description: 'Little green visitor',
    aliases: ['extraterrestrial', 'ufo', 'martian', 'et'],
  },
  {
    id: 'princess',
    name: 'Princess',
    color: '#EC4899',
    shape: 'capsule',
    ...starterModel('princess'),
    size: starterSize('princess'),
    description: 'Regal royal',
    aliases: ['queen', 'royalty', 'monarch'],
  },
  {
    id: 'astronaut',
    name: 'Astronaut',
    color: '#F3F4F6',
    shape: 'capsule',
    ...starterModel('astronaut'),
    size: starterSize('astronaut'),
    description: 'Space explorer',
    aliases: ['spaceman', 'cosmonaut', 'space explorer'],
  },
  {
    id: 'superhero',
    name: 'Superhero',
    color: '#1D4ED8',
    shape: 'capsule',
    ...starterModel('superhero'),
    size: starterSize('superhero'),
    description: 'Caped defender',
    aliases: ['super', 'super hero', 'caped hero', 'flying hero'],
  },
  {
    id: 'minion',
    name: 'Minion',
    color: '#FACC15',
    shape: 'model',
    size: 14,
    description: 'Cheerful yellow helper',
    aliases: ['yellow helper', 'banana buddy'],
    model_url: '/models/minion/FBX/Minion_FBX.fbx',
    preview_scale: 0.14,
    preview_rotation: [0, 0, 0],
  },
  // Creatures — colors are overridden by any color word in the prompt (see
  // extractColor below). The dragon uses the checked-in Metal-generated GLB;
  // the others fall back to primitives until real models ship.
  // Dragon — checked-in multi-part GLB from the metal-dragon tool (see
  // tools/metal-dragon/). Regenerate with `bash tools/metal-dragon/generate.sh`;
  // bounds must stay in sync with the file (see test/editor/model-render-contract.test.js).
  {
    id: 'dragon',
    name: 'Red Metal Dragon',
    color: '#DC2626',
    shape: 'capsule',
    model_url: '/models/red-metal-dragon.glb',
    model_bounds: {
      min: { x: -2.982, y: -1.836, z: -1.983 },
      max: { x: 2.82, y: 2.362, z: 1.983 },
    },
    model_origin_offset: { x: 0, y: 1.836, z: 0 },
    // The only character that is not a metal-starter, so starterSize() cannot
    // reach it. 5.80u across at scale 1, normalised by hand to the same 2.4u
    // as everything else.
    size: 41,
    description: 'Fire-breathing dragon',
    aliases: ['drake', 'wyrm', 'wyvern'],
  },
  {
    id: 'monster',
    name: 'Monster',
    color: '#7C3AED',
    shape: 'sphere',
    ...starterModel('monster'),
    size: starterSize('monster'),
    description: 'One-eyed monster',
    aliases: ['creature', 'beast', 'ogre', 'troll', 'goblin', 'blob'],
  },
  {
    id: 'ghost',
    name: 'Ghost',
    color: '#E5E7EB',
    shape: 'capsule',
    ...starterModel('ghost'),
    size: starterSize('ghost'),
    description: 'Floaty spirit',
    aliases: ['spirit', 'phantom', 'spook', 'boo'],
  },
  // Animals — quadrupeds share the metal-starters quadruped() template; fish/bird
  // have dedicated templates. Sizes calibrated so each reads at ~0.6-0.7u tall.
  {
    id: 'fish',
    name: 'Fish',
    color: '#60A5FA',
    shape: 'capsule',
    ...starterModel('fish'),
    size: starterSize('fish'),
    description: 'Tiny swimmer',
    aliases: ['minnow', 'guppy', 'goldfish', 'trout'],
  },
  {
    id: 'dog',
    name: 'Dog',
    color: '#F59E0B',
    shape: 'capsule',
    ...starterModel('dog'),
    size: starterSize('dog'),
    description: 'Loyal pup',
    aliases: ['doggy', 'hound', 'canine'],
  },
  {
    id: 'puppy',
    name: 'Puppy',
    color: '#F59E0B',
    shape: 'capsule',
    ...starterModel('puppy'),
    size: starterSize('puppy'),
    description: 'Little pup',
    aliases: ['pup'],
  },
  {
    id: 'cat',
    name: 'Cat',
    color: '#F97316',
    shape: 'capsule',
    ...starterModel('cat'),
    size: starterSize('cat'),
    description: 'Sneaky feline',
    aliases: ['kitten', 'kitty', 'feline'],
  },
  {
    id: 'bird',
    name: 'Bird',
    color: '#38BDF8',
    shape: 'sphere',
    ...starterModel('bird'),
    size: starterSize('bird'),
    description: 'Small bird',
    aliases: ['sparrow', 'robin', 'chick', 'chirper'],
  },
  {
    id: 'dinosaur',
    name: 'Dinosaur',
    color: '#16A34A',
    shape: 'capsule',
    ...starterModel('dinosaur'),
    size: starterSize('dinosaur'),
    description: 'Friendly dino',
    aliases: ['dino', 't-rex', 'trex'],
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    color: '#F0ABFC',
    shape: 'capsule',
    ...starterModel('unicorn'),
    size: starterSize('unicorn'),
    description: 'Magical unicorn',
    aliases: ['pony', 'horse'],
  },
  {
    id: 'tree',
    name: 'Tree',
    color: '#16A34A',
    shape: 'cone',
    ...starterModel('tree'),
    size: starterSize('tree'),
    description: 'Leafy tree',
    aliases: ['bush', 'shrub', 'pine', 'fir'],
  },
  {
    id: 'rock',
    name: 'Rock',
    color: '#57534E',
    shape: 'sphere',
    ...starterModel('rock'),
    size: starterSize('rock'),
    description: 'Boulder',
    aliases: ['stone', 'pebble'],
  },
  {
    id: 'pirate',
    name: 'Pirate',
    color: '#8B2635',
    shape: 'capsule',
    ...starterModel('pirate'),
    size: starterSize('pirate'),
    description: 'Daring sea captain',
    aliases: ['buccaneer','captain','sailor'],
  },
  {
    id: 'chef',
    name: 'Chef',
    color: '#F1F0EC',
    shape: 'capsule',
    ...starterModel('chef'),
    size: starterSize('chef'),
    description: 'Cheerful cook',
    aliases: ['cook','baker'],
  },
  {
    id: 'doctor',
    name: 'Doctor',
    color: '#F2F5F7',
    shape: 'capsule',
    ...starterModel('doctor'),
    size: starterSize('doctor'),
    description: 'Kind healer',
    aliases: ['nurse','medic'],
  },
  {
    id: 'explorer',
    name: 'Explorer',
    color: '#AD9A61',
    shape: 'capsule',
    ...starterModel('explorer'),
    size: starterSize('explorer'),
    description: 'Ready for adventure',
    aliases: ['adventurer','scout'],
  },
  {
    id: 'queen',
    name: 'Queen',
    color: '#6B3399',
    shape: 'capsule',
    ...starterModel('queen'),
    size: starterSize('queen'),
    description: 'Regal ruler',
    aliases: ['ruler','monarch'],
  },
  {
    id: 'king',
    name: 'King',
    color: '#991F33',
    shape: 'capsule',
    ...starterModel('king'),
    size: starterSize('king'),
    description: 'Grand ruler',
    aliases: ['emperor'],
  },
  {
    id: 'witch',
    name: 'Witch',
    color: '#4D2970',
    shape: 'capsule',
    ...starterModel('witch'),
    size: starterSize('witch'),
    description: 'Friendly spellcaster',
    aliases: ['sorceress'],
  },
  {
    id: 'diver',
    name: 'Diver',
    color: '#1F3359',
    shape: 'capsule',
    ...starterModel('diver'),
    size: starterSize('diver'),
    description: 'Deep-sea explorer',
    aliases: ['scuba','swimmer'],
  },
  {
    id: 'bear',
    name: 'Bear',
    color: '#734D2E',
    shape: 'box',
    ...starterModel('bear'),
    size: starterSize('bear'),
    description: 'Cuddly and strong',
    aliases: ['teddy','grizzly'],
  },
  {
    id: 'rabbit',
    name: 'Rabbit',
    color: '#EBE0D1',
    shape: 'box',
    ...starterModel('rabbit'),
    size: starterSize('rabbit'),
    description: 'Hoppy and quick',
    aliases: ['bunny','hare'],
  },
  {
    id: 'fox',
    name: 'Fox',
    color: '#D96B24',
    shape: 'box',
    ...starterModel('fox'),
    size: starterSize('fox'),
    description: 'Clever and fast',
    aliases: ['vixen'],
  },
  {
    id: 'panda',
    name: 'Panda',
    color: '#F0F0EE',
    shape: 'box',
    ...starterModel('panda'),
    size: starterSize('panda'),
    description: 'Gentle bamboo lover',
    aliases: ['bamboo'],
  },
  {
    id: 'tiger',
    name: 'Tiger',
    color: '#E6801F',
    shape: 'box',
    ...starterModel('tiger'),
    size: starterSize('tiger'),
    description: 'Bold big cat',
    aliases: ['lion','cub'],
  },
  {
    id: 'penguin',
    name: 'Penguin',
    color: '#212633',
    shape: 'box',
    ...starterModel('penguin'),
    size: starterSize('penguin'),
    description: 'Waddling swimmer',
    aliases: ['bird'],
  },
  {
    id: 'owl',
    name: 'Owl',
    color: '#856142',
    shape: 'box',
    ...starterModel('owl'),
    size: starterSize('owl'),
    description: 'Wise night bird',
    aliases: ['hoot'],
  },
  {
    id: 'parrot',
    name: 'Parrot',
    color: '#D92E2E',
    shape: 'box',
    ...starterModel('parrot'),
    size: starterSize('parrot'),
    description: 'Colourful talker',
    aliases: ['macaw','tropical'],
  },
  {
    id: 'shark',
    name: 'Shark',
    color: '#6B7A8C',
    shape: 'box',
    ...starterModel('shark'),
    size: starterSize('shark'),
    description: 'Toothy swimmer',
    aliases: ['fin'],
  },
  {
    id: 'octopus',
    name: 'Octopus',
    color: '#9E4DA8',
    shape: 'box',
    ...starterModel('octopus'),
    size: starterSize('octopus'),
    description: 'Curious eight-armed friend',
    aliases: ['squid','tentacle'],
  },
  // Objects, vehicles and small creatures. Added because the original 39
  // starters came from only ten silhouettes — fifteen of them the same
  // humanoid recoloured — so the picker looked far more repetitive than its
  // count suggested. These are new shapes, not new palettes.
  {
    id: 'car',
    name: 'Car',
    color: '#D92E33',
    shape: 'box',
    ...starterModel('car'),
    size: starterSize('car'),
    description: 'A little racing car',
    aliases: ['vehicle', 'racer', 'automobile', 'race car'],
  },
  {
    id: 'rocket',
    name: 'Rocket',
    color: '#EB3B2E',
    shape: 'cone',
    ...starterModel('rocket'),
    size: starterSize('rocket'),
    description: 'A spaceship ready for launch',
    aliases: ['spaceship', 'spacecraft', 'launch', 'space'],
  },
  {
    id: 'boat',
    name: 'Boat',
    color: '#8C5423',
    shape: 'box',
    ...starterModel('boat'),
    size: starterSize('boat'),
    description: 'A little sailing boat',
    aliases: ['ship', 'sailboat', 'yacht', 'sail'],
  },
  {
    id: 'airplane',
    name: 'Airplane',
    color: '#387AD9',
    shape: 'box',
    ...starterModel('airplane'),
    size: starterSize('airplane'),
    description: 'A propeller plane',
    aliases: ['plane', 'aeroplane', 'jet', 'flying', 'flight'],
  },
  {
    id: 'train',
    name: 'Train',
    color: '#246E4C',
    shape: 'box',
    ...starterModel('train'),
    size: starterSize('train'),
    description: 'A steam engine',
    aliases: ['locomotive', 'steam engine', 'railway', 'choo choo'],
  },
  {
    id: 'spider',
    name: 'Spider',
    color: '#3D2952',
    shape: 'sphere',
    ...starterModel('spider'),
    size: starterSize('spider'),
    description: 'An eight-legged spider',
    aliases: ['bug', 'arachnid', 'creepy', 'halloween'],
  },
  {
    id: 'crab',
    name: 'Crab',
    color: '#E05C29',
    shape: 'box',
    ...starterModel('crab'),
    size: starterSize('crab'),
    description: 'A snappy little crab',
    aliases: ['shellfish', 'claw', 'beach', 'ocean'],
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    color: '#F28C26',
    shape: 'box',
    ...starterModel('butterfly'),
    size: starterSize('butterfly'),
    description: 'A bright butterfly',
    aliases: ['moth', 'wings', 'insect', 'garden'],
  },
  {
    id: 'bee',
    name: 'Bee',
    color: '#F5C728',
    shape: 'sphere',
    ...starterModel('bee'),
    size: starterSize('bee'),
    description: 'A stripy buzzing bee',
    aliases: ['bumblebee', 'wasp', 'honey', 'insect', 'buzz'],
  },
  {
    id: 'snake',
    name: 'Snake',
    color: '#4A9E43',
    shape: 'box',
    ...starterModel('snake'),
    size: starterSize('snake'),
    description: 'A coiled snake',
    aliases: ['serpent', 'python', 'cobra', 'reptile'],
  },
  {
    id: 'frog',
    name: 'Frog',
    color: '#57B348',
    shape: 'sphere',
    ...starterModel('frog'),
    size: starterSize('frog'),
    description: 'A hopping frog',
    aliases: ['toad', 'amphibian', 'pond', 'ribbit'],
  },
  {
    id: 'turtle',
    name: 'Turtle',
    color: '#6B4D29',
    shape: 'box',
    ...starterModel('turtle'),
    size: starterSize('turtle'),
    description: 'A slow friendly turtle',
    aliases: ['tortoise', 'shell', 'sea turtle'],
  },
  {
    id: 'jellyfish',
    name: 'Jellyfish',
    color: '#F08CC6',
    shape: 'sphere',
    ...starterModel('jellyfish'),
    size: starterSize('jellyfish'),
    description: 'A drifting jellyfish',
    aliases: ['jelly', 'sea creature', 'ocean', 'stingy'],
  },
  {
    id: 'snail',
    name: 'Snail',
    color: '#C78533',
    shape: 'sphere',
    ...starterModel('snail'),
    size: starterSize('snail'),
    description: 'A snail with a spiral shell',
    aliases: ['slug', 'shell', 'garden', 'slow'],
  },
  {
    id: 'house',
    name: 'House',
    color: '#EBDEBF',
    shape: 'box',
    ...starterModel('house'),
    size: starterSize('house'),
    description: 'A little cottage',
    aliases: ['home', 'cottage', 'building', 'hut'],
  },
  {
    id: 'castle',
    name: 'Castle',
    color: '#9E9E99',
    shape: 'cylinder',
    ...starterModel('castle'),
    size: starterSize('castle'),
    description: 'A stone keep with battlements',
    aliases: ['tower', 'fortress', 'keep', 'palace'],
  },
  {
    id: 'mushroom',
    name: 'Mushroom',
    color: '#D13333',
    shape: 'sphere',
    ...starterModel('mushroom'),
    size: starterSize('mushroom'),
    description: 'A spotted toadstool',
    aliases: ['toadstool', 'fungus', 'forest', 'mario'],
  },
  {
    id: 'flower',
    name: 'Flower',
    color: '#F27AAD',
    shape: 'sphere',
    ...starterModel('flower'),
    size: starterSize('flower'),
    description: 'A cheerful flower',
    aliases: ['daisy', 'bloom', 'plant', 'garden', 'petal'],
  },
  {
    id: 'star',
    name: 'Star',
    color: '#FACC38',
    shape: 'cone',
    ...starterModel('star'),
    size: starterSize('star'),
    description: 'A twinkling star',
    aliases: ['sparkle', 'shine', 'space', 'collectible', 'gold star'],
  },
  {
    id: 'chest',
    name: 'Treasure Chest',
    color: '#7A4D29',
    shape: 'box',
    ...starterModel('chest'),
    size: starterSize('chest'),
    description: 'A chest full of treasure',
    aliases: ['treasure', 'loot', 'box', 'pirate chest', 'reward'],
  },
];

/**
 * A tiny color-word extractor for prompt strings. Used by the AI-character
 * route when neither a prefab match nor Meshy nor Claude produces a real
 * color — instead of picking a random one, we honor the color word the kid
 * actually typed.
 *
 * Returns null when no color word is present.
 */
export function extractColor(prompt: string): string | null {
  const t = prompt.toLowerCase();
  const map: Array<[RegExp, string]> = [
    [/\bred\b|\bcrimson\b|\bruby\b|\bscarlet\b/, '#EF4444'],
    [/\borange\b|\bamber\b/, '#F97316'],
    [/\byellow\b|\bgold(en)?\b/, '#FACC15'],
    [/\bgreen\b|\bemerald\b|\blime\b/, '#22C55E'],
    [/\bblue\b|\bazure\b|\bsapphire\b|\bnavy\b/, '#3B82F6'],
    [/\bpurple\b|\bviolet\b|\bindigo\b|\bmagenta\b/, '#8B5CF6'],
    [/\bpink\b|\brose\b/, '#EC4899'],
    [/\bwhite\b|\bsnow\b|\bpale\b/, '#F3F4F6'],
    [/\bblack\b|\bshadow\b|\bdark\b/, '#111827'],
    [/\bgrey\b|\bgray\b|\bsilver\b/, '#9CA3AF'],
    [/\bbrown\b|\btan\b/, '#92400E'],
    [/\bcyan\b|\bturquoise\b|\bteal\b/, '#06B6D4'],
  ];
  for (const [re, hex] of map) if (re.test(t)) return hex;
  return null;
}

/** Raw primitive shapes — matched when the prompt names a shape directly. */
export const BASIC_SHAPES: CharacterPrefab[] = [
  { id: 'cube', name: 'Cube', color: '#60A5FA', shape: 'box', size: 60, description: 'Boxy character', aliases: ['box', 'block', 'square'] },
  { id: 'sphere', name: 'Ball', color: '#F59E0B', shape: 'sphere', size: 60, description: 'Round rolling ball', aliases: ['sphere', 'orb', 'globe'] },
  { id: 'cylinder', name: 'Barrel', color: '#34D399', shape: 'cylinder', size: 60, description: 'Barrel-shaped body', aliases: ['cylinder', 'tube', 'can'] },
  { id: 'cone', name: 'Cone', color: '#A78BFA', shape: 'cone', size: 60, description: 'Pointy top', aliases: ['pointy', 'triangle'] },
  { id: 'pyramid', name: 'Pyramid', color: '#F472B6', shape: 'pyramid', size: 60, description: 'Four-sided pyramid', aliases: ['tetrahedron'] },
  { id: 'torus', name: 'Ring', color: '#FBBF24', shape: 'torus', size: 60, description: 'Donut ring', aliases: ['donut', 'doughnut', 'ring'] },
  { id: 'capsule', name: 'Capsule', color: '#60A5FA', shape: 'capsule', size: 60, description: 'Standing pill', aliases: ['pill'] },
];

/**
 * Best-effort prefab match. Returns the closest CHARACTER_TEMPLATES or
 * BASIC_SHAPES entry, or null if nothing matches confidently.
 *
 * Match strategy (fastest → loosest):
 *   1. Exact id / name match
 *   2. Case-insensitive substring of id / name / alias in the prompt
 *   3. Prompt tokens overlap with name/description/aliases
 *
 * Returns null instead of guessing when confidence is low, so the caller can
 * fall through to Meshy or the AI-property path.
 */
export function matchCharacterPrefab(prompt: string): CharacterPrefab | null {
  const normalized = prompt.trim().toLowerCase();
  if (!normalized) return null;

  const pool = [...CHARACTER_TEMPLATES, ...BASIC_SHAPES];
  const words = normalized.split(/[^a-z0-9]+/).filter(Boolean);
  const wordSet = new Set(words);
  const matchesKeyword = (keyword: string) => {
    const normalizedKeyword = keyword.toLowerCase();
    return normalizedKeyword.includes(' ')
      ? normalized.includes(normalizedKeyword)
      : wordSet.has(normalizedKeyword);
  };

  // A model-backed match wins over primitives; within the model pool, an id or
  // name match beats an alias match so compound prompts resolve to the primary
  // noun ("a knight riding a wyvern" → knight, not dragon-via-wyvern-alias;
  // "red dragon warrior" → dragon, not knight-via-warrior-alias). Ties break by
  // catalog order (first declared wins), matching picker grid order.
  //
  // A MULTI-WORD alias outranks a single-word id, because it is strictly more
  // specific: "a space explorer stuck on mars" is an astronaut, even though the
  // catalog also contains a character whose id is literally "explorer". Without
  // this, adding any character whose name appears inside an existing
  // multi-word alias silently hijacks that alias.
  let bestModel: { prefab: CharacterPrefab; score: number } | null = null;
  for (const prefab of pool) {
    if (!prefab.model_url) continue;
    let score = 0;
    const multiWordAlias = (prefab.aliases ?? []).some(
      (a) => a.includes(' ') && matchesKeyword(a)
    );
    if (multiWordAlias) score = 3;
    else if (matchesKeyword(prefab.id) || matchesKeyword(prefab.name)) score = 2;
    else if ((prefab.aliases ?? []).some(matchesKeyword)) score = 1;
    if (score > (bestModel?.score ?? 0)) bestModel = { prefab, score };
  }
  if (bestModel) return bestModel.prefab;

  // Tier 1: exact id or name.
  for (const p of pool) {
    if (p.id === normalized || p.name.toLowerCase() === normalized) return p;
  }

  // Tier 2: any keyword (id, name, alias) appears as a whole-word match.
  for (const p of pool) {
    const keywords = [p.id, p.name.toLowerCase(), ...(p.aliases ?? [])];
    for (const k of keywords) {
      // Whole-word check — "hero" matches "a brave hero" but not "heroic".
      if (matchesKeyword(k)) return p;
    }
  }

  return null;
}


/**
 * Display order for the picker grid.
 *
 * Deliberately separate from CHARACTER_TEMPLATES, which the AI matcher walks:
 * that matcher breaks ties by array position, so reordering it in place would
 * quietly change which character a prompt resolves to.
 *
 * The problem this solves is what the picker looked like with 59 starters —
 * the first two rows were all humanoids, because that is the order they were
 * added in, and the vehicles and creatures sat below the fold where most
 * children never scroll. A child should see the range in the first screenful.
 *
 * The same list drives the editor's preload, so the models warmed on mount are
 * exactly the ones shown first.
 */
const FEATURED_FIRST = [
  'hero', 'dinosaur', 'car', 'dragon',
  'robot', 'cat', 'rocket', 'unicorn',
  'spider', 'house', 'star', 'mushroom',
  'astronaut', 'frog', 'airplane', 'butterfly',
];

/** CHARACTER_TEMPLATES reordered for display: variety first, then the rest. */
export const PICKER_CHARACTERS: CharacterPrefab[] = (() => {
  const byId = new Map(CHARACTER_TEMPLATES.map((c) => [c.id, c]));
  const featured = FEATURED_FIRST.map((id) => byId.get(id)).filter(Boolean) as CharacterPrefab[];
  const seen = new Set(featured.map((c) => c.id));
  return [...featured, ...CHARACTER_TEMPLATES.filter((c) => !seen.has(c.id))];
})();

/** Builds the exact prefab-first payload returned by generate-character. */
export function buildPrefabCharacterResponse(prompt: string, prefab: CharacterPrefab) {
  return {
    ...prefab,
    color: extractColor(prompt) ?? prefab.color,
    name: prompt.length > 2 ? prompt : prefab.name,
    source: 'prefab' as const,
  };
}
